-- =====================================================================
-- Módulo Control de Gastos (adg) - Esquema MSSQL
--
-- Ajustar los nombres de T_USUARIOS y T_TERCEROS a las tablas reales del
-- sistema si difieren (solo se usan para JOIN de referencia / lookup).
-- =====================================================================

CREATE TABLE GTOS_SOLICITUDES (
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION          NVARCHAR(500)   NOT NULL,
    JUSTIFICACION        NVARCHAR(1000)  NULL,
    VALOR_ESTIMADO       DECIMAL(18,2)   NOT NULL,
    ID_USUARIO_SOLICITA  INT             NOT NULL,
    ID_DPTO              INT             NULL,
    ESTADO               VARCHAR(40)     NOT NULL,
    REQUIERE_ANTICIPO    BIT             NOT NULL DEFAULT 0,
    FECHA_CREACION       DATETIME        NOT NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION   DATETIME        NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE GTOS_COTIZACIONES (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD    INT NOT NULL REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    CONSECUTIVO     TINYINT NOT NULL,        -- 1, 2 o 3
    NOMBRE_ARCHIVO  NVARCHAR(255) NOT NULL,
    RUTA_ARCHIVO    NVARCHAR(500) NOT NULL,
    ES_APROBADA     BIT NOT NULL DEFAULT 0,
    FECHA_CARGA     DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE GTOS_APROBACION_COTIZACION (
    ID                      INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD            INT NOT NULL REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    ID_COTIZACION_APROBADA  INT NULL REFERENCES GTOS_COTIZACIONES(ID),
    ESTADO                  VARCHAR(20) NOT NULL,   -- APROBADO | RECHAZADO
    MOTIVO                  NVARCHAR(500) NULL,
    ID_USUARIO              INT NOT NULL,
    FECHA                   DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE GTOS_ANTICIPOS (
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD         INT NOT NULL UNIQUE REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    BENEFICIARIO         VARCHAR(20) NOT NULL,   -- PROPIO | TERCERO
    TIPO_PERSONA         VARCHAR(20) NOT NULL,   -- NATURAL | JURIDICA
    NIT                  VARCHAR(30) NOT NULL,
    NOMBRES              NVARCHAR(255) NOT NULL,
    TELEFONO             VARCHAR(30) NULL,
    EMAIL                VARCHAR(150) NULL,
    ESTADO_APROBACION    VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE', -- PENDIENTE | APROBADO | RECHAZADO
    MOTIVO_RECHAZO       NVARCHAR(500) NULL,
    ID_USUARIO_APRUEBA   INT NULL,
    FECHA_APROBACION     DATETIME NULL
);
GO

CREATE TABLE GTOS_FACTURAS (
    ID                      INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD            INT NOT NULL UNIQUE REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    NIT_TERCERO             VARCHAR(30) NOT NULL,
    CODIGO_SAP              VARCHAR(30) NULL,
    NOMBRE_TERCERO          NVARCHAR(255) NULL,
    NUMERO_PRELIMINAR_SAP   VARCHAR(50) NOT NULL,
    NUMERO_FACTURA          VARCHAR(50) NOT NULL,
    FECHA_FACTURA           DATE NOT NULL,
    NOMBRE_ARCHIVO          NVARCHAR(255) NOT NULL,
    RUTA_ARCHIVO            NVARCHAR(500) NOT NULL,
    ID_FONDO                TINYINT NOT NULL,     -- 1 ROMA, 2 Fondo proveedor, 3 Nota proveedor
    NUMERO_FONDO            VARCHAR(50) NULL,
    SUBTOTAL                DECIMAL(18,2) NOT NULL,
    IVA                     DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL                   DECIMAL(18,2) NOT NULL
);
GO

CREATE TABLE GTOS_CAUSACION (
    ID                INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD      INT NOT NULL UNIQUE REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    NUMERO_CAUSACION  VARCHAR(50) NOT NULL,
    NOTA              NVARCHAR(500) NULL,
    ID_USUARIO        INT NOT NULL,
    FECHA             DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE GTOS_PAGOS (
    ID                       INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD             INT NOT NULL UNIQUE REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    NUMERO_COMPROBANTE_PAGO  VARCHAR(50) NOT NULL,
    ID_USUARIO               INT NOT NULL,
    FECHA                    DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE GTOS_COMPENSACION (
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD         INT NOT NULL UNIQUE REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    NUMERO_COMPENSACION  VARCHAR(50) NOT NULL,
    ID_USUARIO           INT NOT NULL,
    FECHA                DATETIME NOT NULL DEFAULT GETDATE()
);
GO

-- Bitácora general: TODOS los cambios de estado, motivos y comentarios del flujo.
CREATE TABLE GTOS_FLUJO_HISTORIAL (
    ID               INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITUD     INT NOT NULL REFERENCES GTOS_SOLICITUDES(ID) ON DELETE CASCADE,
    ESTADO_ANTERIOR  VARCHAR(40) NULL,
    ESTADO_NUEVO     VARCHAR(40) NOT NULL,
    ACCION           VARCHAR(60) NOT NULL,
    COMENTARIO       NVARCHAR(1000) NULL,
    ID_USUARIO       INT NOT NULL,
    FECHA            DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE INDEX IX_GTOS_SOLICITUDES_ESTADO   ON GTOS_SOLICITUDES(ESTADO);
CREATE INDEX IX_GTOS_SOLICITUDES_USUARIO  ON GTOS_SOLICITUDES(ID_USUARIO_SOLICITA);
CREATE INDEX IX_GTOS_FLUJO_HISTORIAL_SOL  ON GTOS_FLUJO_HISTORIAL(ID_SOLICITUD);
GO
